In [288]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [289]:
datapath='advertising.csv'
df = pd.read_csv(datapath, encoding="gbk")
df.head()

wechat  weibo  others  sales
0   304.4   93.6   294.4    9.7
1  1011.9   34.4   398.4   16.7
2  1091.1   32.8   295.2   17.3
3    85.5  173.6   403.2    7.0
4  1047.0  302.4   553.6   22.1

In [290]:
df.describe()

wechat       weibo      others       sales
count   200.000000  200.000000  200.000000  200.000000
mean    669.046500  186.112000  244.432000   15.130500
std     390.638071  118.774473  174.228967    5.283892
min       3.200000    0.000000    2.400000    1.600000
25%     338.425000   79.800000  102.000000   11.000000
50%     681.350000  183.200000  206.000000   16.000000
75%     995.675000  292.200000  360.800000   19.050000
max    1348.600000  396.800000  912.000000   27.000000

In [291]:
def normalize_feature(df):
    return (df-df.mean())/df.std()

In [292]:
df = normalize_feature(df)
df.head()

wechat     weibo    others     sales
0 -0.933464 -0.778888  0.286795 -1.027746
1  0.877676 -1.277311  0.883711  0.297035
2  1.080421 -1.290782  0.291387  0.410587
3 -1.493829 -0.105343  0.911261 -1.538733
4  0.967529  0.979066  1.774493  1.319009

In [293]:
df.insert(0,'ones',1)
df.head()

ones    wechat     weibo    others     sales
0     1 -0.933464 -0.778888  0.286795 -1.027746
1     1  0.877676 -1.277311  0.883711  0.297035
2     1  1.080421 -1.290782  0.291387  0.410587
3     1 -1.493829 -0.105343  0.911261 -1.538733
4     1  0.967529  0.979066  1.774493  1.319009

In [294]:
X=df.iloc[:,0:-1]
Y=df.iloc[:,-1]

In [295]:
X = X.values
Y = Y.values
Y.reshape(200,1)

array([[-1.02774617],
       [ 0.29703482],
       [ 0.41058748],
       [-1.53873312],
       [ 1.31900873],
       [ 0.39166204],
       [ 0.18348217],
       [-1.78476387],
       [-0.72493908],
       [-1.08452249],
       [ 0.37273659],
       [-1.95509286],
       [-1.50088223],
       [ 1.37578506],
       [-0.32750479],
       [-0.78171541],
       [-0.95204439],
       [ 0.29703482],
       [-0.5546101 ],
       [-0.53568466],
       [-0.80064085],
       [ 0.71339456],
       [ 1.05405253],
       [-0.61138643],
       [-0.0246977 ],
       [-0.422132  ],
       [-0.87634262],
       [ 0.14563128],
       [ 0.84587266],
       [ 0.37273659],
       [-0.72493908],
       [-1.12237338],
       [-0.08147403],
       [-0.36535567],
       [-1.27377692],
       [-0.59246098],
       [ 0.29703482],
       [ 0.94049987],
       [-1.80368932],
       [-1.61443489],
       [ 1.75429391],
       [ 0.54306558],
       [ 0.37273659],
       [ 1.62181581],
       [-1.21700059],
       [ 1

### 损失函数

In [296]:
def costfunction(X,Y,theta):
    inner = np.power(X @ theta-Y,2)
    return np.sum(inner/(2*len(X)))

In [297]:
theta=np.zeros((4,1))
theta

array([[0.],
       [0.],
       [0.],
       [0.]])

In [298]:
cost_init=costfunction(X,Y,theta)

In [299]:
print(cost_init)

99.5


### 梯度下降函数

In [300]:
def tiduxiajiang(X,Y,theta,alpha,iters):
    costs = []
    for i in range(iters):
        theta = theta -(X.T @ (X@theta - Y))* alpha/len(X)
        cost = costfunction(X,Y,theta)
        costs.append(cost)
        if i%100 ==0:
            print(cost)
    return theta,costs

In [301]:
alpha=0.002
iters=2000
theta,costs=tiduxiajiang(X,Y,theta,alpha,iters)

99.102398
66.40372170518796
44.49392088675849
29.81322349169554
19.97639851133696
13.385218059191175
8.968786960793693
6.009550176350555
4.026708793502103
2.698102725138367
1.8078680850093782
1.2113649277856393
0.8116770246881688
0.5438655002262236
0.3644179560829096
0.24417883954839326
0.1636124254800297
0.10962876972045317
0.07345693406328202
0.04921993720933475


### 最后的结果

In [302]:
theta

array([[-1.00899758e+00,  2.91616187e-01,  4.03097368e-01,
        -1.51066289e+00,  1.29494681e+00,  3.84517171e-01,
         1.80135007e-01, -1.75220545e+00, -7.11714435e-01,
        -1.06473817e+00,  3.65936974e-01, -1.91942722e+00,
        -1.47350250e+00,  1.35068740e+00, -3.21530304e-01,
        -7.67455025e-01, -9.34676796e-01,  2.91616187e-01,
        -5.44492665e-01, -5.25912468e-01, -7.86035222e-01,
         7.00380515e-01,  1.03482406e+00, -6.00233255e-01,
        -2.42471567e-02, -4.14431288e-01, -8.60356009e-01,
         1.42974614e-01,  8.30441892e-01,  3.65936974e-01,
        -7.11714435e-01, -1.10189857e+00, -7.99877469e-02,
        -3.58690698e-01, -1.25054014e+00, -5.81653058e-01,
         2.91616187e-01,  9.23342876e-01, -1.77078565e+00,
        -1.58498368e+00,  1.72229133e+00,  5.33158745e-01,
         3.65936974e-01,  1.59222996e+00, -1.19479955e+00,
         1.03482406e+00, -9.85679436e-02, -6.00233255e-01,
         3.28776581e-01, -1.39918171e+00, -1.45492230e+0