1.reshape()函数：numpy.reshape(a, newshape, order='C'),order表示存储的顺序，'C'是按行储存，'F'是按列储存。
2.一维数组，行向量与列向量
3.一维数组变二维数组
4.一维数组变三维数组
5.视图与副本：使用数组时，记得注意视图和副本的区别，可以用 numpy.shares_memory() 判断两个数组是否指向同一个内存。(reshape()函数返回的是一个视图)
6.矩阵的转置：numpy.transpose() 方法和.T 属性都返回原始数组的转置，两者都返回原始数组的视图，而不是副本
7.扁平化：ravel(), reshape(-1)返回的是一个视图，flatten()返回的是一个副本
8.旋转，翻转数组：旋转：numpy.rot90() 的作用是将一个数组逆时针旋转 90 度，numpy.rot90() 的结果也是返回原始数组的视图，而不是副本。
                 翻转：numpy.flip()
9.堆叠：万能堆叠：numpy.stack() 函数将沿着指定轴将多个数组堆叠在一起，返回一个新的数组；默认轴为 axis = 0。（还分别有沿行堆叠和沿列堆叠）
      拼接：可以用 numpy.concatenate((), axis = 0) 完成数组拼接,axis = 0沿行方向拼接
10.重复：numpy.repeat() 重复的是分别数组中的每个元素,还可以指定具体的轴，以及不同元素重复的次数。
         numpy.tile() 重复的是整个数组
11.合成：numpy.block() 函数用于将多个数组沿不同的轴组合成一个分块矩阵。
   切割：numpy.split() 函数可以将一个数组沿指定轴分割为多个子数组。numpy.split() 接受三个参数：要分割的数组、分割的索引位置、沿着哪个轴进行分割。
   还有一些操作：附加：numpy.append()，插入：numpy.insert()，删除：numpy.delete()。

In [6]:
import numpy as np
a = np.arange(12)
b = np.reshape(a, (2, 3, 2))
c = np.reshape(a, (3, 4))
d = np.reshape(b, -1)
e = np.reshape(a, (4, 3), order = 'F')
b[0, 0, 0] = 100

print(a)
print(b)
print(c)
print(d)
print(e)

[100   1   2   3   4   5   6   7   8   9  10  11]
[[[100   1]
  [  2   3]
  [  4   5]]

 [[  6   7]
  [  8   9]
  [ 10  11]]]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[100   1   2   3   4   5   6   7   8   9  10  11]
[[100   4   8]
 [  1   5   9]
 [  2   6  10]
 [  3   7  11]]


In [16]:
import numpy as np

a = np.array(np.arange(12))
b = np.reshape(a, (2, 6))
c = np.flip(b, axis = 0)#将每一行当成一个整体翻转
d = np.flip(b, axis = 1)#将每一列当成一个整体翻转
e = np.flip(b)#没有axis的话默认将数组沿着所有轴进行翻转

print(a)
print(b)
print(c)
print(d)
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]]
[[ 5  4  3  2  1  0]
 [11 10  9  8  7  6]]
[[11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]


In [8]:
#16-1
import numpy as np

a = np.arange(6)
b = np.reshape(a, (2, 3), order = 'C')
c = np.shares_memory(a, b)

print(a)
print(b)
print(c)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
True


In [18]:
#16-2
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
b = a.flatten(order = 'F')

print(b)

[1 3 5 2 4 6]


In [20]:
#16-3
import numpy as np

a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b = np.reshape(a, (2, 4), order = 'F')

print(b)

[[1 3 2 4]
 [5 7 6 8]]


In [26]:
#16-4
import numpy as np

a = np.random.uniform(low = 0, high = 1, size = 10)
b = np.reshape(a, (10, 1))
c = np.reshape(a, (1, 10), order = 'F')

print(b)
print(c)

[[0.65616117]
 [0.28864737]
 [0.28078443]
 [0.95943213]
 [0.45680883]
 [0.30463598]
 [0.17587691]
 [0.02272885]
 [0.74584646]
 [0.46958939]]
[[0.65616117 0.28864737 0.28078443 0.95943213 0.45680883 0.30463598
  0.17587691 0.02272885 0.74584646 0.46958939]]


In [38]:
#16-5
import numpy as np

# a = np.random.uniform(low = 0, high = 1, size = 144)
a = np.arange(144)
b = np.reshape(a, (12,12))
c = np.split(b, 3, axis = 0)
d = np.split(b, 3, axis = 1)

print(b)
for i in range(3):
    print(c[i])
for i in range(3):
    print(d[i])

[[  0   1   2   3   4   5   6   7   8   9  10  11]
 [ 12  13  14  15  16  17  18  19  20  21  22  23]
 [ 24  25  26  27  28  29  30  31  32  33  34  35]
 [ 36  37  38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71]
 [ 72  73  74  75  76  77  78  79  80  81  82  83]
 [ 84  85  86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107]
 [108 109 110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131]
 [132 133 134 135 136 137 138 139 140 141 142 143]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44 45 46 47]]
[[48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80 81 82 83]
 [84 85 86 87 88 89 90 91 92 93 94 95]]
[[ 96  97  98  99 100 101 102 103 104 105 106 107]
 [108 109 110 111 112 

In [66]:
#16-6
import numpy as np

a = np.arange(40)
b = np.reshape(a[:6], (2, 3))
c = np.reshape(a[6:12], (2, 3))
d = np.concatenate((b, c), axis = 0)
e = np.concatenate((b, c), axis = 1)
# d = np.stack((b, c), axis = 0)
# e = np.stack((b, c), axis = 1)
# f = np.stack((b, c), axis = 2)

print(b)
print(c)
print(d)
print(e)
# print(f)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
